// src/lib/scales.ts — Scale/mode data and logic

import type {
  Chord,
  Derivation,
  DegreeMove,
  KeyAndMode,
  PitchClass,
  RelatedScale,
  ScaleInfo,
  ScaleName,
  Sibling,
  Triad,
} from './types';

/** Interval arrays (semitones from root) for each supported mode/scale. */
export const SCALE_DEFS: Record<ScaleName, number[]> = {
  // Church modes
  'Ionian':      [0, 2, 4, 5, 7, 9, 11],
  'Dorian':      [0, 2, 3, 5, 7, 9, 10],
  'Phrygian':    [0, 1, 3, 5, 7, 8, 10],
  'Lydian':      [0, 2, 4, 6, 7, 9, 11],
  'Mixolydian':  [0, 2, 4, 5, 7, 9, 10],
  'Aeolian':     [0, 2, 3, 5, 7, 8, 10],
  'Locrian':     [0, 1, 3, 5, 6, 8, 10],
  // Pentatonics
  'Major Pentatonic': [0, 2, 4, 7, 9],
  'Minor Pentatonic': [0, 3, 5, 7, 10],
  // Blues
  'Blues':       [0, 3, 5, 6, 7, 10],
};

/**
 * The three remaining 7-note modal families, generated by rotating a parent
 * scale's interval array rather than hand-typing 21 more arrays. Symmetric
 * scales (whole tone, diminished) are deliberately excluded — they'd get no
 * diatonic chord and no siblings (see getSiblings).
 */
const SCALE_PARENTS: Record<string, number[]> = {
  'Melodic Minor':  [0, 2, 3, 5, 7, 9, 11],
  'Harmonic Minor': [0, 2, 3, 5, 7, 8, 11],
  'Harmonic Major': [0, 2, 4, 5, 7, 8, 11],
};

/** Mode names for each parent, in rotation order (index 0 = the parent itself). */
const FAMILY_MODE_NAMES: Record<string, ScaleName[]> = {
  'Melodic Minor':  ['Melodic Minor', 'Dorian b2', 'Lydian Augmented', 'Lydian Dominant', 'Mixolydian b6', 'Locrian #2', 'Altered'],
  'Harmonic Minor': ['Harmonic Minor', 'Locrian #6', 'Ionian #5', 'Ukrainian Dorian', 'Phrygian Dominant', 'Lydian #2', 'Altered bb7'],
  'Harmonic Major': ['Harmonic Major', 'Dorian b5', 'Phrygian b4', 'Lydian b3', 'Mixolydian b2', 'Lydian Augmented #2', 'Locrian bb7'],
};

/**
 * Rotates a parent scale's interval array to start at degree k, renormalizing
 * so the new root is 0. mode(I, k)[j] = (I[(k+j) % n] - I[k] + 12) % 12.
 */
function rotateIntervals(parent: number[], k: number): number[] {
  const n = parent.length;
  return Array.from({ length: n }, (_, j) => (parent[(k + j) % n] - parent[k] + 12) % 12);
}

for (const [family, parent] of Object.entries(SCALE_PARENTS)) {
  FAMILY_MODE_NAMES[family].forEach((name, k) => {
    SCALE_DEFS[name] = rotateIntervals(parent, k);
  });
}

/** Groups of mode names for the settings-panel UI and as the derivation reference pool. */
export const SCALE_FAMILIES: Record<string, ScaleName[]> = {
  'Church Modes':          ['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Aeolian', 'Locrian'],
  'Melodic Minor Modes':   FAMILY_MODE_NAMES['Melodic Minor'],
  'Harmonic Minor Modes':  FAMILY_MODE_NAMES['Harmonic Minor'],
  'Harmonic Major Modes':  FAMILY_MODE_NAMES['Harmonic Major'],
  'Pentatonic & Blues':    ['Major Pentatonic', 'Minor Pentatonic', 'Blues'],
};

/** Scales enabled by default on a fresh install — the original 10, before this expansion. */
export const DEFAULT_ENABLED_SCALES: ScaleName[] = [
  ...SCALE_FAMILIES['Church Modes'],
  ...SCALE_FAMILIES['Pentatonic & Blues'],
];

/** 12 pitch-class display names (0 = C). */
export const ROOT_NAMES: string[] = ['C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B'];

/**
 * Musical knowledge cards for each scale/mode.
 * brightness: 1 (very dark) – 5 (very bright)
 */
export const SCALE_INFO: Record<ScaleName, ScaleInfo> = {
  'Ionian': {
    alias: '= Major scale',
    feel: 'Bright, happy and resolved. The archetypal Western major scale — familiar and uplifting without tension.',
    genres: ['Pop', 'Classical', 'Country', 'Gospel'],
    tip: 'Try ending phrases on the major 7th (leading tone) to create a strong pull back to the root.',
  },
  'Dorian': {
    feel: 'Minor but optimistic — a "cool" minor with a raised 6th that adds a subtle sweetness. Soulful and groove-friendly.',
    genres: ['Jazz', 'Funk', 'Rock', 'Celtic'],
    tip: 'The raised 6th makes II a major chord — lean into the II–V movement for a jazzy flavour over minor.',
  },
  'Phrygian': {
    feel: 'Dark and tense with a distinctly Spanish or Middle-Eastern flavour. The flat 2nd creates immediate drama.',
    genres: ['Flamenco', 'Metal', 'Film Score', 'World'],
    tip: 'The bII chord (the "Phrygian chord") resolves powerfully to I — great for dramatic cadences.',
  },
  'Lydian': {
    feel: 'Dreamy, floating and ethereal. The raised 4th gives it an otherworldly, suspended quality unlike any other major mode.',
    genres: ['Film Score', 'Ambient', 'Prog Rock', 'Jazz'],
    tip: 'Linger on the #4 over a I major chord for that signature "Lydian shimmer" heard in countless film soundtracks.',
  },
  'Mixolydian': {
    feel: 'Major with a bluesy edge — the flat 7th adds earthiness and swagger. Feels natural and unresolved in a satisfying way.',
    genres: ['Blues-Rock', 'Folk', 'Funk', 'Classic Rock'],
    tip: 'Alternate between the I and bVII chords to instantly evoke that anthemic, modal rock sound.',
  },
  'Aeolian': {
    alias: '= Natural minor scale',
    feel: 'Melancholic and expressive — the natural minor. Emotionally rich, cathartic, and universally understood as "sad".',
    genres: ['Rock', 'Metal', 'Classical', 'Pop'],
    tip: 'Raise the 7th to a leading tone (borrowing from harmonic minor) for stronger V–I cadences when you want resolution.',
  },
  'Locrian': {
    feel: 'Deeply unstable and unsettling — the diminished 5th on I makes it avoid functioning as a tonic. Pure tension.',
    genres: ['Metal', 'Avant-garde', 'Film Score'],
    tip: 'Rather than treating it as a home key, use Locrian over a half-diminished (ø7) chord in jazz for the full Locrian colour.',
  },
  'Major Pentatonic': {
    brightness: 5,
    feel: 'Open, spacious and universally singable. Five notes with no semitone tension — everything sounds good.',
    genres: ['Country', 'Folk', 'Gospel', 'Pop'],
    tip: 'Play it starting on the 6th degree and you get the relative minor pentatonic — one shape, two scales for free.',
  },
  'Minor Pentatonic': {
    brightness: 3,
    feel: 'Earthy, soulful and instantly recognisable. The workhorse of rock and blues — raw and direct.',
    genres: ['Blues', 'Rock', 'R&B', 'Hip-Hop'],
    tip: 'Add the b5 "blue note" between 4 and 5 to turn this into the full blues scale for extra grit.',
  },
  'Blues': {
    brightness: 3,
    feel: 'Gritty and expressive. The added blue note (b5) creates a delicious clash that sits between major and minor emotions.',
    genres: ['Blues', 'Jazz', 'Soul', 'Rock'],
    tip: 'Bend into the blue note (b5) from the 4th for maximum expression — that microtonal slide is the heart of blues phrasing.',
  },
};

// ── Melodic minor modes ──────────────────────────────────────
Object.assign(SCALE_INFO, {
  'Melodic Minor': {
    alias: '= Jazz Minor scale',
    feel: 'Minor with a lifted top end — the raised 6th and 7th smooth out the natural minor\'s pull, giving it a sophisticated, "minor major" ambiguity.',
    genres: ['Jazz', 'Fusion', 'Classical', 'Film Score'],
    tip: 'The raised 7th gives a strong leading tone into i while the raised 6th avoids the harsh minor-scale augmented-2nd gap — great for smooth minor-key lines.',
  },
  'Dorian b2': {
    feel: 'Dorian\'s cool minor groove with a Phrygian-style flat 2nd bite added on top — moody and a little exotic without going fully dark.',
    genres: ['Jazz', 'Fusion', 'Flamenco Jazz'],
    tip: 'Use over a minor chord where you want the flamenco-tinged b2 tension resolving down into the root.',
  },
  'Lydian Augmented': {
    feel: 'Lydian pushed further — the raised 4th and raised 5th together create a floating, unresolved shimmer with no perfect 5th to anchor it.',
    genres: ['Jazz', 'Film Score', 'Fusion'],
    tip: 'Sits naturally over a maj7#5 chord — let the #4 and #5 both ring for the full "suspended in space" effect.',
  },
  'Lydian Dominant': {
    feel: 'Bright and unresolved — Lydian\'s floating #4 combined with a bluesy flat 7th. Sometimes called the "overtone scale" because it mirrors the harmonic series.',
    genres: ['Jazz', 'Fusion', 'Funk'],
    tip: 'The classic choice over a dominant 7#11 chord — the #4 keeps it from sounding like plain Mixolydian.',
  },
  'Mixolydian b6': {
    feel: 'Major-ish but wistful — a flat 6th pulls a normally bright Mixolydian toward minor, giving it a bittersweet, almost Spanish-modal quality.',
    genres: ['Jazz', 'Flamenco', 'Fusion'],
    tip: 'Works well over a dominant chord resolving to a minor tonic — the b6 foreshadows the minor destination.',
  },
  'Locrian #2': {
    alias: '= Half-diminished scale',
    feel: 'Locrian\'s instability with a natural 2nd instead of a flat one — still tense from the b5, but less claustrophobic.',
    genres: ['Jazz'],
    tip: 'The go-to scale over a half-diminished (m7b5) chord in a minor ii–V–i — the natural 2nd makes it far more usable than plain Locrian.',
  },
  'Altered': {
    alias: '= Super Locrian scale',
    feel: 'Maximum tension — every alterable note is altered (b9, #9, #11, b13). Built to clash against a dominant chord before it resolves.',
    genres: ['Jazz', 'Bebop', 'Fusion'],
    tip: 'Play it over a V7alt chord resolving down a fifth — the dissonance is the point, and resolution feels earned.',
  },
});

// ── Harmonic minor modes ─────────────────────────────────────
Object.assign(SCALE_INFO, {
  'Harmonic Minor': {
    feel: 'Natural minor with a sharpened 7th — the raised leading tone gives minor keys a strong, classical pull back to the tonic that Aeolian lacks.',
    genres: ['Classical', 'Metal', 'Flamenco', 'Film Score'],
    tip: 'The raised 7th turns V into a major (even dominant) chord — use a V7–i cadence for a dramatic classical resolution.',
  },
  'Locrian #6': {
    feel: 'Locrian\'s instability softened slightly by a natural 6th, giving the diminished tonic a touch more colour to work with.',
    genres: ['Jazz', 'Classical'],
    tip: 'Useful over a m7b5 chord in a harmonic-minor context — the natural 6th distinguishes it from plain Locrian.',
  },
  'Ionian #5': {
    alias: '= Augmented Major scale',
    feel: 'A major scale with its 5th raised into an augmented triad — bright but unstable, like Ionian caught mid-shift.',
    genres: ['Jazz', 'Classical', 'Film Score'],
    tip: 'Pairs with a maj7#5 chord — the augmented triad on top gives an unresolved, searching quality against the major tonic.',
  },
  'Ukrainian Dorian': {
    alias: '= Romanian Minor scale',
    feel: 'Dorian with a raised 4th — minor but with an exotic, Eastern-European lift, sitting between Dorian\'s coolness and harmonic minor\'s drama.',
    genres: ['Klezmer', 'Balkan', 'Jazz', 'Film Score'],
    tip: 'The #4 over a minor chord gives instant "Eastern European" colour — great for klezmer- or gypsy-jazz-flavoured minor vamps.',
  },
  'Phrygian Dominant': {
    alias: '= Spanish/Freygish scale',
    feel: 'The signature Flamenco and Middle-Eastern sound — a major 3rd over a Phrygian b2 and b6 creates immediate exotic drama.',
    genres: ['Flamenco', 'Middle Eastern', 'Klezmer', 'Metal'],
    tip: 'Played over a dominant chord a fifth above a minor tonic (V7 in harmonic minor) — the b2 and b6 are what make it instantly recognisable.',
  },
  'Lydian #2': {
    feel: 'Lydian\'s floating #4 combined with a sharpened 2nd — an unusual, angular brightness rarely heard outside harmonic-minor-derived jazz lines.',
    genres: ['Jazz', 'Fusion'],
    tip: 'Try it over a maj7#11 chord built on the 6th degree of harmonic minor — an uncommon but striking colour choice.',
  },
  'Altered bb7': {
    alias: '= Ultralocrian scale',
    feel: 'The darkest, most dissonant of the seven — a diminished 3rd, 5th and double-flat 7th stack into pure, unresolved tension.',
    genres: ['Jazz', 'Avant-garde'],
    tip: 'Reserved for a diminished 7th chord resolving to a minor tonic a half-step below — treat it as a passing colour, not a home base.',
  },
});

// ── Harmonic major modes ─────────────────────────────────────
Object.assign(SCALE_INFO, {
  'Harmonic Major': {
    feel: 'Major scale with a flattened 6th — bright at the bottom, melancholic at the top, giving it a bittersweet, cinematic quality.',
    genres: ['Classical', 'Film Score', 'Jazz'],
    tip: 'The b6 lets you borrow a minor iv chord in an otherwise major key for an instant, poignant color shift.',
  },
  'Dorian b5': {
    feel: 'Dorian\'s cool minor groove with a flattened 5th — the usually stable perfect 5th collapses into a diminished one, adding unease.',
    genres: ['Jazz', 'Fusion'],
    tip: 'Fits a m7b5 chord with a natural 6th — a less common half-diminished colour than Locrian #2.',
  },
  'Phrygian b4': {
    feel: 'Phrygian\'s dark b2 tension deepened further by a flattened 4th, collapsing the scale\'s middle into tight, dissonant clusters.',
    genres: ['Flamenco', 'Metal', 'Avant-garde'],
    tip: 'A rare, highly chromatic-sounding minor colour — use sparingly as a tension scale rather than a resting point.',
  },
  'Lydian b3': {
    alias: '= Lydian Minor scale',
    feel: 'Lydian\'s dreamy raised 4th over a minor 3rd — floating and unresolved, but with a melancholic edge Lydian itself doesn\'t have.',
    genres: ['Jazz', 'Film Score', 'Fusion'],
    tip: 'Works over a minor(maj7) chord with a #11 — keeps Lydian\'s shimmer while grounding it in minor.',
  },
  'Mixolydian b2': {
    feel: 'Mixolydian\'s bluesy flat 7th combined with a flamenco-style flat 2nd — earthy and exotic at the same time.',
    genres: ['Flamenco', 'Jazz', 'World'],
    tip: 'Sits over a dominant 7 chord where you want Phrygian-Dominant colour without losing the natural 6th.',
  },
  'Lydian Augmented #2': {
    feel: 'Lydian Augmented pushed one step further with a sharpened 2nd — dense, bright, and among the most unusual scales here.',
    genres: ['Jazz', 'Avant-garde'],
    tip: 'A rare-use colour scale for a maj7#5 chord with added chromatic tension — approach it as an ear-opener, not a workhorse.',
  },
  'Locrian bb7': {
    feel: 'Locrian\'s instability taken to its extreme with a double-flat 7th, removing any hint of a leading tone back to the root.',
    genres: ['Jazz', 'Avant-garde'],
    tip: 'The most unstable scale of the set — use it only as a brief passing colour over a fully diminished chord.',
  },
});

/**
 * Returns a 1–11 brightness rating for a mode. For 7-note scales this is a
 * pure function of the interval sum: `sum(intervals) - 32` exactly matches
 * every hand-authored church-mode value on the old 1–7 scale (Locrian sums
 * to 33 → 1 … Lydian sums to 39 → 7); rescaled to `- 30` here so the wider
 * 31–41 sum range of the new families spreads across a full 1–11 meter
 * instead of clamping most of them to 7. Odd-cardinality scales (pentatonics,
 * blues) aren't comparable by sum across different note counts, so they keep
 * their hand-picked SCALE_INFO value.
 */
export function getBrightness(modeName: ScaleName): number {
  const intervals = SCALE_DEFS[modeName];
  if (intervals.length === 7) {
    const sum = intervals.reduce((a, b) => a + b, 0);
    return sum - 30;
  }
  return SCALE_INFO[modeName].brightness!;
}

// ── Derivation: "closest known scale" + what changed ─────────

/** Degree name for each of the 12 semitone values, relative to the major scale. */
const DEGREE_NAME_BY_INTERVAL = ['1', '♭2', '2', '♭3', '3', '4', '♭5', '5', '♭6', '6', '♭7', '7'];

/** Ionian and Aeolian need no derivation — everything else derives from a known scale. */
const ANCHOR_MODES = new Set(['Ionian', 'Aeolian']);

/** Display label used in derivation text ("= Major with #4", not "= Ionian with #4"). */
const REF_LABEL: Record<string, string> = {
  Ionian: 'Major', Aeolian: 'Minor',
  Dorian: 'Dorian', Phrygian: 'Phrygian', Lydian: 'Lydian',
  Mixolydian: 'Mixolydian', Locrian: 'Locrian',
};

/** Tie-break order when two church-mode references are equally close. */
const FAMILIARITY = ['Ionian', 'Aeolian', 'Dorian', 'Mixolydian', 'Phrygian', 'Lydian', 'Locrian'];

const CHURCH_MODES = SCALE_FAMILIES['Church Modes'];

/**
 * Index-wise diff between two equal-length interval arrays. Every scale here
 * is sorted starting at 0, so scale degree N is always index N-1 in both
 * arrays — no note-matching/alignment logic needed.
 * delta: +-1 = #/b, +-2 = ##/bb
 */
function diffScales(refIntervals: number[], curIntervals: number[]): DegreeMove[] {
  const moves: DegreeMove[] = [];
  for (let i = 0; i < refIntervals.length; i++) {
    if (refIntervals[i] === curIntervals[i]) continue;
    let delta = curIntervals[i] - refIntervals[i];
    if (delta > 6) delta -= 12;
    if (delta < -6) delta += 12;
    moves.push({ degree: i + 1, delta });
  }
  return moves;
}

/**
 * Renders one degree move as e.g. "#4" / "b7" / "##5". A positive move off an
 * Aeolian (natural minor) reference is spelled with a natural sign instead of
 * a sharp — raising Aeolian's flat 6th/7th back to the unaltered pitch reads
 * as "natural 6", not "sharp 6" (standard usage: "Dorian = Minor with natural 6").
 */
function alterationSymbol(move: DegreeMove, refName: string): string {
  const abs = Math.abs(move.delta);
  if (move.delta > 0 && refName === 'Aeolian' && abs === 1) return `♮${move.degree}`;
  const sign = move.delta > 0 ? '♯' : '♭';
  return sign.repeat(abs) + move.degree;
}

/** Picks the candidate reference with fewest moves, tie-broken by FAMILIARITY. */
function derivationFromCandidates(intervals: number[], candidateNames: ScaleName[]) {
  let best: { refName: ScaleName; moves: DegreeMove[]; rank: number } | null = null;
  for (const refName of candidateNames) {
    const moves = diffScales(SCALE_DEFS[refName], intervals);
    const rank = FAMILIARITY.indexOf(refName);
    if (!best || moves.length < best.moves.length ||
        (moves.length === best.moves.length && rank < best.rank)) {
      best = { refName, moves, rank };
    }
  }
  return {
    refName: best!.refName,
    refLabel: REF_LABEL[best!.refName] ?? best!.refName,
    kind: 'alteration' as const,
    moves: best!.moves,
    degreeIndices: best!.moves.map(m => m.degree - 1),
  };
}

/** Handles the three scales whose cardinality differs from their closest relative. */
function deriveOtherCardinality(modeName: ScaleName, intervals: number[]) {
  if (modeName === 'Major Pentatonic' || modeName === 'Minor Pentatonic') {
    const refName = modeName === 'Major Pentatonic' ? 'Ionian' : 'Aeolian';
    const missing = SCALE_DEFS[refName].filter(iv => !intervals.includes(iv));
    return {
      refName, refLabel: REF_LABEL[refName], kind: 'subset' as const,
      missingDegreeNames: missing.map(iv => DEGREE_NAME_BY_INTERVAL[iv]),
      degreeIndices: [],
    };
  }
  // Blues
  const added = intervals.filter(iv => !SCALE_DEFS['Minor Pentatonic'].includes(iv));
  return {
    refName: 'Minor Pentatonic', refLabel: 'Minor Pentatonic', kind: 'superset' as const,
    addedDegreeNames: added.map(iv => DEGREE_NAME_BY_INTERVAL[iv]),
    degreeIndices: added.map(iv => intervals.indexOf(iv)),
  };
}

/**
 * Finds the closest known scale to `modeName` and what changed, so the UI can
 * show e.g. "= Major with #4". Returns null for Ionian/Aeolian, which are
 * anchors carrying their own `alias` text instead.
 */
export function getDerivation(modeName: ScaleName): Derivation | null {
  if (ANCHOR_MODES.has(modeName)) return null;
  const intervals = SCALE_DEFS[modeName];

  if (intervals.length !== 7) return deriveOtherCardinality(modeName, intervals);

  if (CHURCH_MODES.includes(modeName)) {
    return derivationFromCandidates(intervals, ['Ionian', 'Aeolian']);
  }

  // Prefer a church mode named inside this scale's own name (Lydian Dominant -> Lydian).
  const named = CHURCH_MODES.find(m => modeName.includes(m));
  return derivationFromCandidates(intervals, named ? [named] : CHURCH_MODES);
}

/**
 * Formats a derivation object into UI text, e.g. "Major with #4" or
 * "Minor Pentatonic plus b5". Returns null for anchors (no derivation).
 */
export function formatDerivation(derivation: Derivation | null): string | null {
  if (!derivation) return null;
  if (derivation.kind === 'subset') {
    return `${derivation.refLabel} without ${derivation.missingDegreeNames.join(' and ')}`;
  }
  if (derivation.kind === 'superset') {
    return `${derivation.refLabel} plus ${derivation.addedDegreeNames.join(' ')}`;
  }
  const symbols = derivation.moves.map(m => alterationSymbol(m, derivation.refName)).join(' ');
  return `${derivation.refLabel} with ${symbols}`;
}

// ── Siblings: same root, one degree moved ────────────────────

/**
 * Renames a note a semitone up or down. Raise drops a flat, else adds a
 * sharp; lower drops a sharp, else adds a flat — correct for single
 * alterations (D->D#, F#->F, Ab->A, Bb->Bbb) though remote enharmonic
 * spellings can still drift, same tradeoff ROOT_NAMES already makes app-wide.
 */
function alterName(noteName: string, direction: 'raise' | 'lower'): string {
  if (direction === 'raise') {
    return noteName.endsWith('b') ? noteName.slice(0, -1) : noteName + '#';
  }
  return noteName.endsWith('#') ? noteName.slice(0, -1) : noteName + 'b';
}

/**
 * Finds sibling scales: same root, same cardinality, exactly one degree
 * moved by a semitone. Drawn from all 31 scales regardless of which are
 * enabled — seeing a disabled sibling is discovery, not noise.
 */
export function getSiblings(rootPitchClass: PitchClass, modeName: ScaleName): Sibling[] {
  const intervals = SCALE_DEFS[modeName];
  const siblings: Sibling[] = [];
  for (const [otherName, otherIntervals] of Object.entries(SCALE_DEFS)) {
    if (otherName === modeName || otherIntervals.length !== intervals.length) continue;
    const moves = diffScales(intervals, otherIntervals);
    if (moves.length !== 1) continue;
    const [move] = moves;
    const curNoteName = ROOT_NAMES[(rootPitchClass + intervals[move.degree - 1]) % 12];
    const newNoteName = alterName(curNoteName, move.delta > 0 ? 'raise' : 'lower');
    siblings.push({
      rootName: ROOT_NAMES[rootPitchClass],
      modeName: otherName,
      noteChange: `${curNoteName}→${newNoteName}`,
    });
  }
  return siblings;
}

/** Returns a Set of pitch classes (0–11) belonging to the scale. */
export function getScaleNotes(rootPitchClass: PitchClass, modeName: ScaleName): Set<PitchClass> {
  const intervals = SCALE_DEFS[modeName];
  if (!intervals) throw new Error(`Unknown mode: ${modeName}`);
  return new Set(intervals.map(i => (rootPitchClass + i) % 12));
}

/**
 * Returns diatonic triads for 7-note modes (stacked thirds within the scale).
 * For pentatonic/blues scales returns an empty array — no conventional triads.
 */
export function getDiatonicTriads(rootPitchClass: PitchClass, modeName: ScaleName): Triad[] {
  const intervals = SCALE_DEFS[modeName];
  if (!intervals || intervals.length !== 7) return [];

  const triads: Triad[] = [];
  const degreeNames = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'];

  for (let d = 0; d < 7; d++) {
    // Root, third, fifth of triad (scale degrees d, d+2, d+4)
    const r = (rootPitchClass + intervals[d]) % 12;
    const t = (rootPitchClass + intervals[(d + 2) % 7]) % 12;
    const f = (rootPitchClass + intervals[(d + 4) % 7]) % 12;

    // Determine quality from interval between root and third
    const thirdInterval = (t - r + 12) % 12;
    const fifthInterval = (f - r + 12) % 12;

    let quality = '';
    if (thirdInterval === 4 && fifthInterval === 7) quality = '';        // major
    else if (thirdInterval === 3 && fifthInterval === 7) quality = 'm';  // minor
    else if (thirdInterval === 3 && fifthInterval === 6) quality = '°';  // diminished
    else if (thirdInterval === 4 && fifthInterval === 8) quality = '+';  // augmented

    const rootName = ROOT_NAMES[r];
    triads.push({
      label: `${degreeNames[d]} — ${rootName}${quality}`,
      notes: [r, t, f],
    });
  }
  return triads;
}

/**
 * Returns the semitone step sizes between consecutive scale degrees,
 * including the wrap-around step back to the next octave root.
 * @param intervals — sorted interval array from SCALE_DEFS
 */
export function getStepSizes(intervals: number[]): number[] {
  const steps: number[] = [];
  for (let i = 0; i < intervals.length; i++) {
    const next = i + 1 < intervals.length ? intervals[i + 1] : 12;
    steps.push(next - intervals[i]);
  }
  return steps;
}

/**
 * Finds all (root, mode) combinations whose pitch-class set is identical
 * to the given scale, excluding the input scale itself.
 */
export function findRelatedScales(rootPitchClass: PitchClass, modeName: ScaleName): RelatedScale[] {
  const target = getScaleNotes(rootPitchClass, modeName);
  const results: RelatedScale[] = [];
  for (let r = 0; r < 12; r++) {
    for (const mode of Object.keys(SCALE_DEFS)) {
      if (r === rootPitchClass && mode === modeName) continue;
      const candidate = getScaleNotes(r, mode);
      if (candidate.size === target.size && [...target].every(n => candidate.has(n))) {
        results.push({ rootName: ROOT_NAMES[r], modeName: mode });
      }
    }
  }
  return results.sort((a, b) => {
    const ra = ROOT_NAMES.indexOf(a.rootName);
    const rb = ROOT_NAMES.indexOf(b.rootName);
    return ra !== rb ? ra - rb : a.modeName.localeCompare(b.modeName);
  });
}

/**
 * Picks a random key and mode and returns everything the UI needs.
 * @param enabledModes  Optional list of mode names to pick from.
 */
export function randomKeyAndMode(enabledModes: ScaleName[] | null = null): KeyAndMode {
  const modeNames = (enabledModes && enabledModes.length > 0)
    ? enabledModes
    : Object.keys(SCALE_DEFS);
  const modeName  = modeNames[Math.floor(Math.random() * modeNames.length)];
  const rootPitchClass = Math.floor(Math.random() * 12);
  const rootName = ROOT_NAMES[rootPitchClass];
  const scaleNotes = getScaleNotes(rootPitchClass, modeName);
  const triads     = getDiatonicTriads(rootPitchClass, modeName);
  return { rootPitchClass, rootName, modeName, scaleNotes, triads };
}

/**
 * Picks one random triad from the triads array.
 * Falls back to a tonic triad placeholder when triads is empty (pentatonic/blues).
 * @param rootPitchClass  used for fallback
 */
export function pickRandomChord(triads: Triad[], rootPitchClass: PitchClass = 0): Chord {
  if (triads.length === 0) {
    return { label: `${ROOT_NAMES[rootPitchClass]} (root)`, notes: [rootPitchClass] };
  }
  return triads[Math.floor(Math.random() * triads.length)];
}
